#!/bin/bash
# Install the repo's git hooks. Run once after cloning:  ./scripts/install-hooks.sh
#
#   pre-push           — the shared-queue guard: refuses to ship other lanes'
#                        commits, names the blocking run and its owner. It was
#                        GENERATED by the python server, which was deleted at
#                        792ce1f — so nothing regenerated it and it survived as
#                        an orphan in ONE checkout (AMUX-2940).
#   prepare-commit-msg — stamps Amux-Session on every commit, `(human)` when
#                        there is no session (AMUX-2567). Until 2026-08-11 this
#                        hook was NOT installed by this script: it existed as a
#                        hand-placed file in one checkout and nowhere else, so a
#                        fresh clone produced untrailered commits that the push
#                        guard must read as foreign.
#   pre-commit         — secret scan + Rust/client-JS syntax, and the shim that
#                        calls the staged-guard below
#   amux-staged-guard  — cross-session sweep protection (AMUX-1730)
#
# WHY THIS NOW INSTALLS TWO FILES (2026-08-09). It used to install only
# pre-commit, on the grounds that amux-staged-guard was a GENERATED artifact:
# the Python server wrote it per work_dir and injected its own shim. That was
# right while python ran. amux-server.py is now deleted and nothing in the rust
# server generates the hook, so the "the server will install it" advice this
# script printed was false, and — worse — overwriting pre-commit here DELETED
# the shim the retired python had injected, turning the guard off while
# printing "ok ... matches".
#
# So the tracked copies are now the ONLY producer. If a generator ever comes
# back, remove them here in the same commit that adds it (the 2026-08-06 revert
# explains what a second producer costs).
#
# USAGE
#   ./scripts/install-hooks.sh                 # this repo (both files)
#   ./scripts/install-hooks.sh /path/to/repo   # ANOTHER checkout: guard only
#   ./scripts/install-hooks.sh --all           # every checkout that already has it
#
# WHY THE OTHER-CHECKOUT MODE EXISTS (2026-08-10). The guard is installed in
# nine checkouts on this machine; eight of them are not amux and have their own
# `pre-commit` (a repo-specific hook with the amux shim injected at the top).
# Only ONE of the nine was reachable by this script, because it resolved
# `$ROOT` from the CURRENT repo and then read `$ROOT/scripts/git-hooks/` —
# which exists nowhere but amux. So after the python generator was deleted,
# every non-amux checkout was frozen on whatever the generator last wrote and
# nothing could update it: eight stale guards, all still addressing the retired
# port, with no supported way to fix them. Sources come from the AMUX checkout
# (where this script lives) and the TARGET is an argument.
#
# The foreign mode NEVER writes `pre-commit`. Those files are the other repo's,
# they carry that repo's own checks (jekyll builds, `pre-commit run`, secret
# scans), and amux's tracked pre-commit runs Rust/client-JS checks that are
# meaningless there. Overwriting one would destroy a user's hook as a side
# effect of a refactor (ethos rule 8) — and it is exactly the mistake this
# script already made once, in the other direction, by overwriting amux's
# pre-commit and silently deleting the shim. It reports instead.
set -e
# Sources always come from the amux checkout this script lives in, never from
# the target — that is the whole bug the foreign mode fixes.
SRC="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# --- foreign checkout: install the guard, verify, never touch their pre-commit
# THE TRACKED MODE IS PART OF THE PROTECTION (AMUX-2663). install here uses
# -m 0755 and so masks a wrong mode at the source — which is exactly how the
# guard sat tracked as 100644 while every checkout that ran this script looked
# fine. Any checkout that did NOT run it (a fresh clone, cp -p, tar) got a
# non-executable guard, `[ -x ]` in pre-commit failed, and cross-session sweep
# protection was silently OFF. Assert the source mode so it cannot regress
# behind this script's own success.
check_tracked_guard_mode() {
  local mode
  mode=$(git -C "$SRC" ls-files -s scripts/git-hooks/amux-staged-guard 2>/dev/null | awk '{print $1}')
  if [ "$mode" != "100755" ]; then
    echo "  FAIL scripts/git-hooks/amux-staged-guard is tracked as ${mode:-<untracked>}, not 100755." >&2
    echo "       Every checkout that does not run this script gets a NON-EXECUTABLE guard," >&2
    echo "       pre-commit's [ -x ] test fails, and sweep protection is off with one line" >&2
    echo "       on stderr. Fix: git update-index --chmod=+x scripts/git-hooks/amux-staged-guard" >&2
    return 1
  fi
  echo "  ok   scripts/git-hooks/amux-staged-guard is tracked executable (100755)"
  return 0
}

install_guard_only() {
  local target="$1" fail=0
  if [ ! -d "$target/.git/hooks" ] && [ ! -d "$target/.git" ]; then
    echo "  SKIP $target — no .git/hooks (not a checkout, or a linked worktree)" >&2
    return 0
  fi
  # THE EFFECTIVE HOOKS DIR, resolved FIRST (MG-1484/MG-1485 follow-up). This
  # function used to install into $target/.git/hooks unconditionally while its
  # own pre-push CHECK below resolved core.hooksPath — split-brain in one
  # function. In mixpeek (hooksPath=.githooks) that meant every refresh landed
  # in a directory git never consults: the resurrection guard was live in the
  # repo where it was authored and DARK in the repo where the incident
  # happened, and a verification grep on .git/hooks read the dead copy as
  # proof. A custom hooksPath dir is usually TRACKED (repo-owned, committed),
  # so we never overwrite divergent files there — mixpeek's copy is a
  # deliberate merge carrying local additions that a blind install would have
  # destroyed. Missing files are installed (and must then be committed in that
  # repo); divergent ones are classified by the guard-features tokens below.
  local hooksdir="$target/.git/hooks" hp tracked_hooks=0
  hp=$(git -C "$target" config core.hooksPath 2>/dev/null || true)
  if [ -n "$hp" ]; then
    case "$hp" in /*) hooksdir="$hp" ;; *) hooksdir="$target/$hp" ;; esac
    case "$hooksdir" in "$target/.git/"*) ;; *) tracked_hooks=1 ;; esac
    if [ ! -d "$hooksdir" ]; then
      echo "  WARN $target core.hooksPath=$hp does not exist — git runs NO hooks there" >&2
      return 1
    fi
  fi

  # place <file>: .git-owned dir -> install+verify (ours to manage).
  # Tracked dir -> equal: ok; missing: install + tell them to commit it;
  # differs: report, never overwrite (the copy is the repo owner's).
  place() {
    local name="$1" src="$SRC/scripts/git-hooks/$1" dst="$hooksdir/$1"
    if [ "$tracked_hooks" -eq 0 ]; then
      install -m 0755 "$src" "$dst"
      if cmp -s "$src" "$dst"; then
        echo "  ok   $dst matches the tracked source"
      else
        echo "  FAIL $dst differs after install" >&2
        return 1
      fi
      return 0
    fi
    if [ -f "$dst" ] && cmp -s "$src" "$dst"; then
      echo "  ok   $dst matches the canonical source (tracked hooks dir)"
      return 0
    fi
    if [ ! -f "$dst" ]; then
      install -m 0755 "$src" "$dst"
      echo "  note $dst INSTALLED into a TRACKED hooks dir — commit it in that repo or it"
      echo "       exists only in this worktree"
      return 0
    fi
    # Divergent tracked copy: classify by canonical feature tokens so a STALE
    # copy (dark in the repo where it runs) is distinguishable from a
    # deliberate local merge. Tokens come from the canonical's own
    # `# guard-features:` line; absence of the line means cmp is all we have.
    # THE NUMERIC MARKER RUNS FIRST, AND IT OUTRANKS THE TOKENS (AF-431 / MR-44).
    #
    # The token loop below is `grep -qi "$t" "$dst"` — a bare, case-insensitive
    # SUBSTRING hunt anywhere in the file. mixpeek-research measured what that
    # costs: mixpeek's GUARD_VERSION 4 copy of amux-staged-guard, ~215 lines and
    # five versions behind, passed as "carries every canonical feature" because
    # the literal string AMUX-2946 appears at its line 75 in an unrelated comment
    # about retired ports. A token that a file can satisfy by TALKING about the
    # feature cannot certify that it HAS the feature, and the failure is silent
    # and in the reassuring direction.
    #
    # Marker format, mirroring mixpeek's dc21a0d489 so both repos agree: a file
    # declaring `# guard-features:` carries exactly one anchored integer, either
    # `^GUARD_VERSION = N` (self-reports at runtime) or `^# guard-version: N`
    # (no runtime need). Anchored, so a mention in a comment cannot supply it.
    #
    # FAILS CLOSED. A declaring canonical whose TARGET has no marker reads STALE,
    # because "no marker" is what every copy predating this convention looks
    # like, and treating unknown as current is how the dark-guard shape survived
    # for eighteen days.
    local ver_of stale_ver="" src_v dst_v
    ver_of() {
      local f="$1" v
      v=$(grep -m1 -E '^GUARD_VERSION[[:space:]]*=[[:space:]]*[0-9]+' "$f" 2>/dev/null \
          | grep -oE '[0-9]+' | head -1)
      [ -n "$v" ] || v=$(grep -m1 -E '^# guard-version:[[:space:]]*[0-9]+' "$f" 2>/dev/null \
          | grep -oE '[0-9]+' | head -1)
      printf '%s' "$v"
    }
    src_v=$(ver_of "$src"); dst_v=$(ver_of "$dst")
    if [ -n "$src_v" ]; then
      if [ -z "$dst_v" ]; then
        stale_ver="no version marker at all (canonical is $src_v)"
      elif [ "$dst_v" -lt "$src_v" ] 2>/dev/null; then
        stale_ver="version $dst_v against a canonical of $src_v"
      fi
    fi
    local feats missing_feats="" t
    feats=$(grep -m1 '^# guard-features:' "$src" | cut -d: -f2-)
    for t in $feats; do
      grep -qi "$t" "$dst" || missing_feats="$missing_feats $t"
    done
    if [ -n "$stale_ver" ]; then
      echo "  WARN $dst is STALE — $stale_ver" >&2
      echo "       This is the MG-1485 dark-guard shape, caught NUMERICALLY (AF-431): the" >&2
      echo "       copy that RUNS is behind the canonical. Feature tokens agree only when" >&2
      echo "       the version does; a token can be satisfied by a file that merely MENTIONS" >&2
      echo "       the feature (MR-44: a v4 copy passed on AMUX-2946 in a comment about" >&2
      echo "       retired ports). Merge $src into it — do not blind-copy, the vendored file" >&2
      echo "       may carry local additions worth keeping — bump its marker, commit there." >&2
      if [ -n "$missing_feats" ]; then
        echo "       Tokens also missing:$missing_feats" >&2
      else
        echo "       Tokens all PRESENT, which is exactly why this needed a number." >&2
      fi
      fail=1
    elif [ -n "$missing_feats" ]; then
      echo "  WARN $dst is STALE — missing canonical feature(s):$missing_feats" >&2
      echo "       This is the MG-1485 dark-guard shape: the copy that RUNS lacks what the" >&2
      echo "       canonical enforces. Merge $src into it (do not blind-copy: the vendored" >&2
      echo "       file may carry local additions worth keeping), then commit in that repo." >&2
      fail=1
    else
      if [ -n "$src_v" ]; then
        echo "  note $dst diverges from canonical but carries every canonical feature AND"
        echo "       version $dst_v >= $src_v — reads as a deliberate local merge; left untouched"
      else
        echo "  note $dst diverges from canonical but carries every canonical feature —"
        echo "       reads as a deliberate local merge; left untouched (canonical declares no"
        echo "       version marker, so tokens are all this can check)"
      fi
    fi
    return 0
  }

  place "amux-staged-guard" || fail=1
  # THE SESSION STAMP (AMUX-2567). Installed alongside the guard because the
  # guard's attribution is only as good as the trailer: with no
  # prepare-commit-msg, every commit in this checkout is untrailered, the push
  # recipe in CLAUDE.md says to "treat as foreign", and a peer's ordinary work
  # is indistinguishable from a hook-bypassing graft.
  #
  # It was NOT installed by this script before — it existed as a hand-placed
  # file in one checkout's .git/hooks and nowhere else, so a fresh clone got
  # silent non-attribution and looked fine. Unlike pre-commit (which we refuse
  # to rewrite, because it is the repo owner's), prepare-commit-msg is entirely
  # ours: nothing else claims it, so installing it is safe.
  place "prepare-commit-msg" || fail=1
  # append-only-push-guard (MG-1483): the stale-republish data-loss guard —
  # a stale shared checkout committing FRUSTRATIONS.md silently reverted 10
  # pushed entry-lines with no conflict. The FILE is safe to drop anywhere
  # (self-contained, fail-open); the CALL belongs to the repo owner's
  # pre-push, so check it and hand over the line, never edit theirs.
  place "append-only-push-guard" || fail=1
  if [ -f "$hooksdir/pre-push" ] && grep -q 'append-only-push-guard' "$hooksdir/pre-push"; then
    echo "  ok   $target pre-push calls append-only-push-guard"
  else
    echo "  WARN $target pre-push does NOT call append-only-push-guard — stale-republish" >&2
    echo "       protection is OFF there (hooks dir: $hooksdir). Add near the top:" >&2
    echo '         aog="$(git rev-parse --git-path hooks)/append-only-push-guard"' >&2
    echo '         if [ -x "$aog" ]; then "$aog" "$@" <&0 || exit 1; fi' >&2
  fi
  # The shim is the whole chain: an installed guard nothing calls is a file, not
  # a guard. We do not write their pre-commit, so all we can do is check it and
  # hand over the exact lines — which is the honest move, not a silent no-op.
  local pc="$hooksdir/pre-commit"
  if [ -f "$pc" ] && grep -q 'amux-staged-guard' "$pc" && grep -q '"\$g" || exit 1' "$pc"; then
    echo "  ok   $target pre-commit calls amux-staged-guard"
  else
    echo "  WARN $target pre-commit does NOT call amux-staged-guard — sweep protection is OFF there." >&2
    echo "       This script will not edit another repo's pre-commit. Add these 3 lines near the top:" >&2
    echo '         g="$(dirname -- "$0")/amux-staged-guard"' >&2
    echo '         if [ -x "$g" ]; then "$g" || exit 1; fi' >&2
    fail=1
  fi
  # SHIM RESOLUTION (mixpeek 1721501b81): presence in the effective dir is
  # NECESSARY AND NOT SUFFICIENT — the consuming shim's lookup path is a
  # second variable. mixpeek's pre-commit resolved guards via ../.git/hooks/
  # (per-clone, untracked) while the guard sat vendored right next to the
  # shim, so a fresh clone skipped it with only a stderr warning. A shim that
  # references .git/hooks WITHOUT a dirname-based resolution does not travel;
  # one that prefers dirname($0) with .git/hooks as fallback is fine.
  if [ "$tracked_hooks" -eq 1 ]; then
    local shim
    for shim in "$hooksdir/pre-commit" "$hooksdir/pre-push"; do
      [ -f "$shim" ] || continue
      if grep -q '\.git/hooks/' "$shim" && ! grep -q 'dirname' "$shim"; then
        echo "  WARN $shim resolves guards via .git/hooks/ only — per-clone and untracked, so" >&2
        echo "       a FRESH CLONE skips the guard even with the vendored copy next to the" >&2
        echo '       shim. Prefer "$(dirname -- "$0")/<guard>" with .git/hooks as fallback.' >&2
        fail=1
      fi
    done
  fi
  return $fail
}

if [ "${1:-}" = "--all" ]; then
  # Bounded scan, and it PRINTS its bounds: a discovery step that silently
  # missed a checkout would report "all clear" over an unpatched hook, which is
  # the same class of false-green as a grep that could not have matched.
  roots="${AMUX_HOOK_SCAN_ROOTS:-$HOME/Dev}"
  echo "scanning for installed amux guards under: $roots (override: AMUX_HOOK_SCAN_ROOTS)"
  check_tracked_guard_mode || true
  allfail=0
  found=0
  # shellcheck disable=SC2086
  while IFS= read -r g; do
    repo="${g%/.git/hooks/amux-staged-guard}"
    found=$((found + 1))
    if [ "$repo" = "$SRC" ]; then continue; fi   # self is handled below
    install_guard_only "$repo" || allfail=1
  done < <(find $roots -maxdepth 6 -type f -path '*/.git/hooks/amux-staged-guard' -not -path '*/node_modules/*' 2>/dev/null | sort)
  echo "  ($found checkouts had the guard installed)"
  [ "$allfail" -eq 0 ] || echo "one or more checkouts need attention (see WARN/FAIL above)" >&2
  # fall through to install into the amux checkout itself
elif [ -n "${1:-}" ]; then
  check_tracked_guard_mode || true
  install_guard_only "$(cd "$1" && pwd)"
  exit $?
fi
check_tracked_guard_mode || true

ROOT="$SRC"

# WHERE THE HOOKS ACTUALLY LIVE — `git rev-parse --git-path hooks`, never
# "$ROOT/.git/hooks" (2026-08-26). In a linked WORKTREE `.git` is a FILE, not a
# directory, so the hardcoded path is not a directory at all and every install
# below died with `install: cannot stat ... Not a directory` after the script had
# already printed its first `ok` line — a half-run that leaves the checkout with
# NO guards while looking like it started fine.
#
# This script already knew: line ~85 skips a linked worktree by name, and the
# WARN at ~182 tells OTHER hooks to resolve guards this exact way. Only its own
# install path still spelled the path by hand.
#
# The resolved dir is the git COMMON dir, shared by the main checkout and every
# worktree — which is correct and is why the `--all` sweep skips worktrees: one
# install covers them all.
HOOKS="$(git -C "$ROOT" rev-parse --git-path hooks 2>/dev/null)"
case "$HOOKS" in /*) : ;; ?*) HOOKS="$ROOT/$HOOKS" ;; *) HOOKS="$ROOT/.git/hooks" ;; esac
mkdir -p "$HOOKS"

install -m 0755 "$ROOT/scripts/git-hooks/pre-commit" "$HOOKS/pre-commit"
install -m 0755 "$ROOT/scripts/git-hooks/amux-staged-guard" "$HOOKS/amux-staged-guard"
install -m 0755 "$ROOT/scripts/git-hooks/prepare-commit-msg" "$HOOKS/prepare-commit-msg"
install -m 0755 "$ROOT/scripts/git-hooks/pre-push" "$HOOKS/pre-push"
install -m 0755 "$ROOT/scripts/git-hooks/append-only-push-guard" "$HOOKS/append-only-push-guard"
install -m 0755 "$ROOT/scripts/git-hooks/post-commit" "$HOOKS/post-commit"

# THE FIFTH GUARD, which is not a git hook and had no installer at all (AF-409).
#
# ~/.claude/settings.json invokes `python3 ~/.amux/hooks/git-shared-guard.py` as a
# PreToolUse hook, a path OUTSIDE any checkout. Everything above installs into
# .git/hooks; nothing installed this one, so a repo edit reached nobody until a
# human copied it by hand.
#
# Measured 2026-09-02: the running copy was 148 lines behind and byte-identical to
# a58a53cf, while the repo copy carried e782b68a's fix for a command-substitution
# BYPASS (AMUX-3932). Both forms were run through both copies directly:
#   echo "$(git add -A)"             old: ALLOWED   new: blocked
#   python3 <<EOF ... $(git add -A)  old: ALLOWED   new: blocked
# `git add -A` on a shared checkout is the command AF-316 exists to refuse, and for
# three days it was one layer of quoting away from succeeding.
#
# Installed only when the destination directory already exists: this script runs in
# checkouts that are not amux hosts, and creating ~/.amux there would be inventing
# state on somebody else's machine.
SHARED_GUARD_DEST="${AMUX_SHARED_GUARD_DEST:-$HOME/.amux/hooks/git-shared-guard.py}"
if [ -d "$(dirname "$SHARED_GUARD_DEST")" ]; then
  install -m 0755 "$ROOT/scripts/git-hooks/git-shared-guard.py" "$SHARED_GUARD_DEST"
fi

# THE READ ROUTER, the same shape as the guard above (AMUX-4544). settings.json
# runs `python3 ~/.amux/hooks/large-read-guard.py` on every Read and Bash call,
# and only install.sh ever placed it, so a commit to the router reached no lane.
# Measured 2026-09-14: the running copy was byte-identical to its first commit,
# 6bce0158, eight days after 4c068e80 (GMA-123) stopped it recommending the text
# summarizer for images. Same existence rule as the guard: no ~/.amux/hooks, no
# amux host, nothing invented.
READ_ROUTER_DEST="${AMUX_READ_ROUTER_DEST:-$HOME/.amux/hooks/large-read-guard.py}"
READ_ROUTER_SRC="$ROOT/scripts/hooks/large-read-guard.py"
# Source-exists too: a checkout without the router (an older branch, a trimmed
# fixture) must skip it, not fail the whole install.
if [ -d "$(dirname "$READ_ROUTER_DEST")" ] && [ -f "$READ_ROUTER_SRC" ]; then
  install -m 0755 "$READ_ROUTER_SRC" "$READ_ROUTER_DEST"
fi

# Verify rather than announce (ethos #7): compare what landed against its source,
# so a stale installed copy cannot hide behind a success message. That drift was
# real and security-relevant — the AC-239 secret patterns (Clerk, R2, Slack,
# GitLab) sat in the tracked hook while .git/hooks/pre-commit was months old, so
# commits printed "Security scan passed" from a scanner that could match none of
# them.
fail=0
for h in pre-commit amux-staged-guard prepare-commit-msg pre-push post-commit append-only-push-guard; do
  if cmp -s "$ROOT/scripts/git-hooks/$h" "$HOOKS/$h"; then
    echo "  ok   $HOOKS/$h matches scripts/git-hooks/$h"
  else
    echo "  FAIL $HOOKS/$h differs from scripts/git-hooks/$h" >&2
    fail=1
  fi
done

# The PreToolUse guard gets the same treatment, and it is the one that needed it:
# the six above at least had an installer that someone could forget to run, and
# this had none to forget. Reported as SKIP rather than ok when the destination is
# absent, because "not an amux host" and "installed correctly" are different facts
# and a silent pass would merge them (AF-409).
if [ -d "$(dirname "$SHARED_GUARD_DEST")" ]; then
  if cmp -s "$ROOT/scripts/git-hooks/git-shared-guard.py" "$SHARED_GUARD_DEST"; then
    echo "  ok   $SHARED_GUARD_DEST matches scripts/git-hooks/git-shared-guard.py"
  else
    echo "  FAIL $SHARED_GUARD_DEST differs from scripts/git-hooks/git-shared-guard.py" >&2
    fail=1
  fi
else
  echo "  SKIP $SHARED_GUARD_DEST — no ~/.amux/hooks on this machine (not an amux host)"
fi
if [ ! -f "$READ_ROUTER_SRC" ]; then
  echo "  SKIP $READ_ROUTER_DEST — this checkout has no scripts/hooks/large-read-guard.py"
elif [ -d "$(dirname "$READ_ROUTER_DEST")" ]; then
  if cmp -s "$READ_ROUTER_SRC" "$READ_ROUTER_DEST"; then
    echo "  ok   $READ_ROUTER_DEST matches scripts/hooks/large-read-guard.py"
  else
    echo "  FAIL $READ_ROUTER_DEST differs from scripts/hooks/large-read-guard.py" >&2
    fail=1
  fi
else
  echo "  SKIP $READ_ROUTER_DEST — no ~/.amux/hooks on this machine (not an amux host)"
fi

# The shim is the whole chain: an installed guard that pre-commit never calls is
# a file, not a guard. Check the LINK, not just the two files — this is exactly
# the failure that shipped when pre-commit was overwritten without it.
if grep -q 'amux-staged-guard' "$HOOKS/pre-commit" \
   && grep -q '"\$g" || exit 1' "$HOOKS/pre-commit"; then
  echo "  ok   pre-commit calls amux-staged-guard"
else
  echo "  FAIL pre-commit does NOT call amux-staged-guard — sweep protection is OFF" >&2
  fail=1
fi

# And the guard is only a guard if the SERVER routes its endpoint. Unrouted, it
# fails open and (before 2026-08-09) said nothing: POST /api/git/staged-guard
# answered 405 for the whole rust cutover, ~1,147 calls an hour, every one
# swallowed. Report it here, where someone is already looking at hooks.
#
# The base URL comes from the guard's OWN resolver, imported rather than
# re-spelled: it self-heals a stale inherited `AMUX_URL` (see the docstring on
# `amux_base_url`). Checking a different address than the guard will use would
# make this line report on a server the guard never talks to.
BASE="$(python3 -c "
import importlib.machinery, sys
m = importlib.machinery.SourceFileLoader('amux_guard', '$ROOT/scripts/git-hooks/amux-staged-guard').load_module()
print(m.amux_base_url())" 2>/dev/null)" || BASE=""
[ -n "$BASE" ] || BASE="${AMUX_URL:-https://localhost:8824}"
URL="$BASE/api/git/staged-guard"
code=$(curl -sk -o /dev/null -w '%{http_code}' -m 3 -X POST \
        -H 'Content-Type: application/json' -d '{}' "$URL" 2>/dev/null || echo 000)
case "$code" in
  400|200) echo "  ok   server routes POST /api/git/staged-guard (HTTP $code)" ;;
  000)     echo "  note amux server not reachable at $URL — could not check the endpoint" ;;
  404|405|501)
    # Loud, but NOT `fail=1`: the installer's exit code is a verdict on what it
    # installed, and a stale server is not something it can fix. The guard
    # itself now prints this on every commit, which is the enforcement point.
    echo "  WARN server does NOT route POST /api/git/staged-guard (HTTP $code) —" >&2
    echo "       the guard fails open on every commit until the amux server is updated." >&2 ;;
  *)       echo "  note POST /api/git/staged-guard answered HTTP $code" ;;
esac

[ "$fail" -eq 0 ] || exit 1
echo "hooks installed: secret scan + Rust/client-JS syntax + cross-session staged-guard."
